[[news]]
date = "2025-08"
content = "在第十四届全国海洋航行器与设计大赛国赛中获得国家级特等奖。"

[[news]]
date = "2025-07"
content = "在第十四届全国海洋航行器与设计大赛西北赛区获得一等奖（唯一完成人）。"

[[news]]
date = "2025-04"
content = "在中国大学生工程实践与创新能力大赛中获得两项省级一等奖。"

[[news]]
date = "2024-10"
content = "获评西北工业大学优秀大学生。"
